# Site settings
title: Victor's Data Science Blog
url: "http://vchen007.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >Hello! This is my site where I display projects!

# Your information
email: vchen007@gmail.com
author: Victor Chen
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: Hello! This is my site where I display projects!
#twitter_username: twitter_username
github_username:  http://vchen007.github.io
profile_links:
  Email: "mailto:vchen007@gmail.com"
  #GitHub: "http://vchen007.github.io"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    #Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
